server:
    port: 8080
    jwt:
        secret: 13513d8e52501d43b64a336e296b6cde #studev-courage-1922 as MD5 => 256 bits
        algorithm: HS256
        age: 3600000 # 1 hour 
spring:
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        password: 123
        url: jdbc:sqlserver://localhost:1433;databaseName=DB_SUPER;trustServerCertificate=true;
        username: sa
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServer2012Dialect
                format_sql: true
        show-sql: false
    mail:
        host: smtp.gmail.com
        username: '[your email]'
        password: '[your email is password]'
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    security:
        oauth2:
            client:
                registration:
                    facebook: #(Website > Site URL > input: http://localhost:8080)
                        client-id: 3099872300308338
                        client-secret: 7f20e392a12da9854192105cd654943e
                    github: #(Authorization callback URL: http://localhost:8080)
                        client-id: 33ea60d57f1fb102412c
                        client-secret: 0b7ecdc29aaf668c5c1651b2a651d2a927705014
                    google: #(Authorized redirect URIs: http://localhost:8080/login/oauth2/code/google)
                        client-id: 537360767428-p1ju5l6rutjk34qocc8a4anlqh2hqhsp.apps.googleusercontent.com
                        client-secret: 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
            resourceserver:
                    jwt:
                        issuer-uri: https://idp.example.com/issuer
                        jwk-set-uri: https://idp.example.com/jwks

    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB